### ISSUE TITLE
Wine 2.0

### ISSUE THREAD

**Issue by Translator5** [brezerk/q4wine#104]
>wine2.0
Linux Mint 18.1
q4wine 1.3.3

After the release of Wine 2.0 q4wine wont recognize my wine installations or something like that.
It simply wont start anything, even the winecfg.

While other applications like pywinery works fine :confused:

**Comment by brezerk** [comment]
Hi @Translator5 

can you enable the logging and provide the output for app startup please?

**Comment by Translator5** [comment]
`user@LM ~/desk $ q4wine
[ii] Loading translation:  "q4wine_de_DE"
Could not resolve property : radialGradient3709
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : linearGradient5167
Could not resolve property : linearGradient5167
Could not resolve property : linearGradient5167
Could not resolve property : linearGradient5167
Could not resolve property : radialGradient3709
Could not resolve property : linearGradient5167
Could not resolve property : radialGradient3709
Could not resolve property : radialGradient3709
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : linearGradient3592
Could not resolve property : linearGradient7999
Could not resolve property : radialGradient2943
Could not resolve property : radialGradient2943

[ii] Loading translation:  "q4wine_de_DE"
"--prefix"
"--nice"
"--program-bin"
"--wrkdir"
Exec string:
/usr/bin/env  WINEPREFIX='/home/user/.wine'  WINESERVER='/usr/bin/wineserver'  WINELOADER='/usr/bin/wine-preloader'  WINEDLLPATH='/opt/wine-staging/lib'  WINEARCH='win32'  WINEDEBUG='-all'  /bin/sh -c "cd '/home/user/desk' &&   '/usr/bin/wine'   'winecfg.exe'  2>&1 "
Exit code:
256
App STDOUT and STDERR output:
wine: WINEARCH set to win32 but '/home/user/.wine' is a 64-bit installation.

[ii] Loading translation:  "q4wine_de_DE"
"--prefix"
"--nice"
"--program-bin"
"--wrkdir"`

**Comment by brezerk** [comment]
Well..

```
wine: WINEARCH set to win32 but '/home/user/.wine' is a 64-bit installation.
```

It seems like you have wine arch option set to 'win32', while wineprefix is a 64-bit installation.

Try go to: Prefixes -> Edit this prefix -> General -> Architecture -> Default -> Save

**Comment by brezerk** [comment]
In general, you don't need to set `Architecture` option manually. Using `Default` will let Wine to decide the architecture by its own. So it is the best choice.

 `Architecture` option needs to be overridden only if you would like wine to _create_ and use specific arch version.

Also, it is impossible to switch the arch versions win32 <-> win64 or vice versa on runtime. You will need to recreate the prefix from scratch.

**Comment by Translator5** [comment]
> Try go to: Prefixes -> Edit this prefix -> General -> Architecture -> Default -> Save

By clicking on Save q4wine crashes.

**Comment by brezerk** [comment]
>By clicking on Save q4wine crashes.

O_o

Can you send me `~/.config/q4wine/default.conf` and `~/.config/q4wine/db/generic.dat` please?

**Comment by Translator5** [comment]
[here](https://gist.github.com/Translator5/1c0f1539eb2ac17a3bf8861f8a4999fd)

**Comment by brezerk** [comment]
thank you. but I need db file `~/.config/q4wine/db/generic.dat` too. feel free to email me to brezerk@gmail.com

**Comment by brezerk** [comment]
hm..... Are you able to reproduce the segfault? I have tried to use provided files and had no luck.

**Comment by Translator5** [comment]
Segfault? You mean the issue? If yes, I do still have the problem. Cant use q4wine right now.

**Comment by Translator5** [comment]
> Loader: /opt/wine-staging/bin/wine-preloader
> Loader:  /opt/wine-staging/bin/wine64-preloader
That was the fault!

Its right when you use it so;
> Loader: /opt/wine-staging/bin/wine
> Loader:  /opt/wine-staging/bin/wine64

All works fine again!
Thanks anyway!

**Comment by brezerk** [comment]
Hi @Translator5 

Cool. However, I would like to confirm this use case:

> > Try go to: Prefixes -> Edit this prefix -> General -> Architecture -> Default -> Save
> 
> By clicking on Save q4wine crashes.

Are you still able to reproduce this crash?

Thanks

**Comment by Translator5** [comment]
@brezerk nope all works fine, that was the false configuration :laughing:
