### ISSUE TITLE
Q4Wine Launch Error

### ISSUE THREAD

**Issue by PadreAdamo** [brezerk/q4wine#105]
I just installed and reinstalled Q4Wine multiple times to try and fix the error I'm receiving. Launching Q4wine for an escalated terminal works fine. However, launching Q4wine via shortcut or vanilla terminal, I get the following error:

"Cannot find or execute the 'fusermount' binary. Make sure that this binary is available by search PATH variable and see also INSTALL file for application depends."

Distro: OpenSUSE Tumbleweed

whereis fusermount 
/usr/bin

**Comment by tehnick** [comment]
> I just installed and reinstalled Q4Wine multiple times

These actions are meaningless.

> Cannot find or execture the 'fusermount' binary.

Your problem is in program settings which you may fix in settings dialog or in text file `~/.config/q4wine/default.conf`. Or you may delete this file at all and setup all settings from scratch after restarting of application.

**Comment by brezerk** [comment]
Hi @PadreAdamo yes, as @tehnick mentioned, it seems like you have an old (probably wrong) path configured in the `~/.config/q4wine/default.conf` settings file. You may wish to chenge it via q4wine setting dialog `File -> Settings` or `Ctrl + W`.

But probably, the error message should be much more clear and user friendly :)

**Comment by PadreAdamo** [comment]
I don't have a default.conf inside of that directory (~/.config/q4wine).

What settings do I change inside of File settings? There are quite a bit of paths there inside (SU, sudo, etc.)

**Comment by brezerk** [comment]
Hi @PadreAdamo 

Um... Wait...

```
Q4wine does not launch without using elevated permissions--KDESU or su
```

q4wine does not need root privileges to operate (except some exceptions like mounting `iso` or running `nice` command).

I assume you have `~/.config/q4wine` directory owned by the root user?
Can you show output for the following commands please?

```
# id
# ls -al ~/.config/q4wine

**Comment by PadreAdamo** [comment]
padreadamo@new-host-4:~> id
uid=1000(padreadamo) gid=100(users) groups=100(users),472(wheel)
padreadamo@new-host-4:~> ls -al ~/.config/q4wine
total 4
drwxr-xr-x 1 padreadamo users   80 Apr 18 19:17 .
drwx------ 1 padreadamo users 1516 Apr 19 19:25 ..
drwxr-xr-x 1 padreadamo users   22 Apr 17 16:57 db
-rw------- 1 padreadamo users   49 Apr 18 19:17 .directory
drwxr-xr-x 1 padreadamo users    0 Apr 17 16:56 icons
drwxr-xr-x 1 padreadamo users    0 Apr 17 16:56 prefixes
drwxr-xr-x 1 padreadamo users    0 Apr 17 16:56 scripts
drwxr-xr-x 1 padreadamo users    0 Apr 17 16:56 theme
drwxr-xr-x 1 padreadamo users   10 Apr 17 16:56 tmp

**Comment by brezerk** [comment]
interesting...
ok. and can you show  output for this command as well please?

```
ls -al ~/.config/q4wine/db
```

**Comment by PadreAdamo** [comment]
padreadamo@new-host-4:~> ls -al ~/.config/q4wine/db
total 40
drwxr-xr-x 1 padreadamo users    22 Apr 17 16:57 .
drwxr-xr-x 1 padreadamo users    80 Apr 18 19:17 ..
-rw-r--r-- 1 padreadamo users 40960 Apr 17 16:57 generic.dat
padreadamo@new-host-4:~>

**Comment by brezerk** [comment]
um.... from the permissions perspective everything looks pretty good (except the fact, you have no default.conf file for some reasons) so I see no particular reason, why q4wine won't be able to run as a regular user...

ok. so, what error are you getting when executing q4wine as a regular user (padreadamo) ?

**Comment by PadreAdamo** [comment]
It's the same fusermount binary error when running as a regular user. 

"Cannot find or execute the 'fusermount' binary. Make sure that this binary is available by search PATH variable and see also INSTALL file for application depends."

**Comment by brezerk** [comment]
ah... ic.

can you show output for this command (as a regular user please):

```
# which fusermount
```

**Comment by PadreAdamo** [comment]
padreadamo@new-host-4:~> which fusermount
which: no fusermount in (/home/padreadamo/bin:/usr/local/bin:/usr/bin:/bin)

**Comment by brezerk** [comment]
hm.. it seems like you have no `fusermount` binary installed on your system. do you have `fuse-utils` package installed?

**Comment by brezerk** [comment]
(or probably PATH it missing sbin directories). Are you able to get the fusermount path via `which` using sudo\su?

**Comment by PadreAdamo** [comment]
I don't see fuse-utils installed. I have: fuse, fuseiso, gvfs-fuse, libfuse2, libfuse2-32bit,libulockmgr1

I can reach the fusermount directory from root terminal.

padreadamo@new-host-4:~> which fusermount
which: no fusermount in (/home/padreadamo/bin:/usr/local/bin:/usr/bin:/bin)

**Comment by brezerk** [comment]
>I can reach the fusermount directory from root terminal.

which one path it is installed in?

**Comment by PadreAdamo** [comment]
It shows it installed in: /usr/bin/fusermount

**Comment by brezerk** [comment]
um :)
ok... can you show please?

```
# id
# ls -al /usr/bin/fusermount
```

**Comment by PadreAdamo** [comment]
new-host-4:/home/padreadamo # ls -al /usr/bin/fusermount
-rwsr-x--- 1 root root 31552 Oct 16  2016 /usr/bin/fusermount

**Comment by brezerk** [comment]
oh. funny.
for some reasons only root user is allowed to run `fusermount` binary.
not sure if it is really specific to SUSE.

```
[ himera ] brezerk@pts/0:4  ~ $
> 04/21/17 15:05:49 EEST > ls -al /usr/bin/fusermount
-rws--x--x 1 root root 31168 Dec 21 00:00 /usr/bin/fusermount
```

you may wish to adjust the permissions

**Comment by PadreAdamo** [comment]
Fixed! I changed the permissions on that file and all is well. Thank you very much for your help. Do you folks have a patreon or donation page? I use Q4wine on a number of my machines including on machines i built for my friends.

**Comment by brezerk** [comment]
you are welcome. glad you find q4wine useful.

as for donation: at this moment paypal does not accept incoming transactions for Ukraine yet and the other donations options are not really works for most of the people.

so currently the only way to help q4wine project:
* help to translate q4wine http://i18n.brezblock.org.ua/
* report bugs :)
* there is also `q4wine-next` project running, so feature requests are really welcome: https://github.com/brezerk/q4wine/issues/69

**Comment by PadreAdamo** [comment]
Okay! Thank you. I will do what I can for the project. Thank you!
