### ISSUE TITLE
HiDPI support?

### ISSUE THREAD

**Issue by jkw** [brezerk/q4wine#112]
Anyone tried the interface on a 4k monitor? Some dialogs are shrinked, icons are tiny etc.

Some screenshots:
![skarmbild fran 2017-08-01 22-11-53](https://user-images.githubusercontent.com/388872/28845013-e954c356-7706-11e7-8d9f-50f9615022a2.png)
![skarmbild fran 2017-08-01 22-12-27](https://user-images.githubusercontent.com/388872/28845020-ed1e31ac-7706-11e7-84fd-d9b846605895.png)

**Comment by brezerk** [comment]
hi @jkw 

I don't think so. At least I have no 4k monitor yet :)
you can try use '+' and '-' buttons (they supposed to enlarge/reduce) the icon size.

if there are are others elements needs to be adjusted -- feel free to report and I'll try to fix them.

**Comment by jkw** [comment]
> you can try use '+' and '-' buttons (they supposed to enlarge/reduce) the icon size.

Neither of them is working?

**Comment by brezerk** [comment]
which one version are you using? works pretty well for me:

![image](https://user-images.githubusercontent.com/23820/29108834-48aa1b48-7ce9-11e7-8864-c242c9ebd789.png)
![image](https://user-images.githubusercontent.com/23820/29108861-654c237c-7ce9-11e7-9e18-bbec1febaa2f.png)
![image](https://user-images.githubusercontent.com/23820/29108880-7a84cf82-7ce9-11e7-8508-63f626e3b635.png)

**Comment by jkw** [comment]
Oh, I tried the + and - on my keyboard... found the icons in the interface, they worked! :D
![skarmbild fran 2017-08-09 16-29-31](https://user-images.githubusercontent.com/388872/29126956-ffa04b7a-7d1f-11e7-81bf-189c8df2fd4b.png)

**Comment by brezerk** [comment]
hm... I think it will good idea to add this key bindings, yes =)

also, when you get the comfortable size for your icons: can you show me output for this command please?

```
# grep IconSize ~/.config/q4wine/default.conf
```
