### ISSUE TITLE
Static code analysis: errors and warnings

### ISSUE THREAD

**Issue by tehnick** [brezerk/q4wine#116]
How about fixing errors and warnings [found](https://tehnick.net/sibuserv/projects/q4wine) by static code analyzer if you will have a spare time?

Current list from `cppcheck` tool: https://tehnick.net/sibuserv/projects/q4wine/v1.3.5-26-gc0fdb67/StaticCodeAnalysis/cppcheck.html/index.html

**Comment by brezerk** [comment]
should be fixed: https://github.com/brezerk/q4wine/commit/961a07c5629ba7104120b81e3f8453bc2c9be856

thanks

**Comment by tehnick** [comment]
Confirmed. Thanks.
