### ISSUE TITLE
Wine stock icons to be organised through Q4Wine

### ISSUE THREAD

**Issue by es20490446e** [brezerk/q4wine#117]
When you install Q4Wine, it populates the menu with all kind of Wine shortcuts. It would be nicer if instead only the Q4Wine shortcut was shown.

This is because most stock Wine icons are rarely used, they have a more intuitive organisation on Q4Wine, and having many icons makes harder to notice which applications are installed.

![deepinscreenshot_20171108002841](https://user-images.githubusercontent.com/9594332/32523516-e79441a6-c41b-11e7-9b20-ad4efe8c36b3.png)

**Comment by brezerk** [comment]
Hi @es20490446e 

Well... 
Some notes:
q4wine does create it's own icon structure like follows: `~/.local/share/applications/q4wine/<prefix_name>/<folder>`.

So it regular app list you probably can see something like this:
![image](https://user-images.githubusercontent.com/23820/32540637-f7579048-c475-11e7-8ded-e25d98124bb4.png)
![image](https://user-images.githubusercontent.com/23820/32540660-084e4964-c476-11e7-9210-101b92c85bc3.png)
![image](https://user-images.githubusercontent.com/23820/32540753-499ca4f6-c476-11e7-81d9-38c3c748cc54.png)

however, wine also creating the *.desktop files in the `~/.local/share/applications/wine` directory by it's own. And unfortunately I can't restrict wine from doing this :)

The only solution for you is to remove `~/.local/share/applications/wine` directory.
I can add an q4wine option to do this as a part of *desktop files generation (Note: it will be disabled by default) 

Let me know if it works for you.

**Comment by es20490446e** [comment]
Thank you.

Those icons doesn't appear when installing Wine alone, at least not in Arch Linux. They don't even appear when launching winecfg, removing the directory you mentioned, or installing any of the Q4Wine dependencies.

The icons only appear when launching Q4Wine, in "~/.local/share/applications/q4wine". If you delete them, on the next Q4Wine launch, the program recreates them.

**Comment by brezerk** [comment]
hm.. um... 

probably I am getting you wrong :)

so let's clarify:
which one icons you would like *not* to be present/created?

* icons located in the `~/.local/share/applications/wine` (the stock ones)
* icons located in the `~/.local/share/applications/q4wine`
* or both?

**Comment by es20490446e** [comment]
I mean the ones at:
`~/.local/share/applications/q4wine/Default/system`

**Comment by brezerk** [comment]
Git it

**Comment by es20490446e** [comment]
Thanks to you! 🥇

**Comment by brezerk** [comment]
Note: it will be reworked a bit more. But here you are the initial update https://github.com/brezerk/q4wine/commit/597a0e88232167719c88f195edbb53b4ed7d0f08

Added "Export 'system' folder" option (disabled by default. I am agree: stock Wine icons are a bit messy and are rarely used):
![image](https://user-images.githubusercontent.com/23820/32752421-ca79dfb2-c8d1-11e7-86bc-cc8519e61d5f.png)

Note: in order to get rid of old icons you need to click 'Remove desktop menu entries' first (Or remove it manually) Then click 'Regenerate desktop menu' or restart q4wine.

**Comment by es20490446e** [comment]
Looks good to me. Many thanks 😛
