### ISSUE TITLE
First Startup Wizard - Methinks it is Orko

### ISSUE THREAD

**Issue by Connor84** [brezerk/q4wine#118]
I had q4wine and wine installed in my Fedora 26 and they ran great. Recently I reinstalled and upgraded to F27. Now when I try to use q4wine it opens with a First Startup Wizard box. It did not have to do this before. I don't know what to enter for "Console application settings: Binary, (and) Arguments". I like q4wine because it allowed me to enter a virtual desktop and it automatically created desktop links for games which wine by itself does not always do.. (and I don't know how to myself)

**Comment by brezerk** [comment]
Hi @Connor84 

q4wine requires one of following console terminals to be installed:

* xterm
* konsole (a part of KDE environemnt)

if you are using different console terminal -- let me know.

**Comment by Connor84** [comment]
After a little digging, my Fedora 27 uses gnome-terminal.  Should I install xterm or konsole, just for q4wine?

**Comment by brezerk** [comment]
By looking into code i see no logic for `gnome-terminal` detection at the wizard stage.

If you wish to use it, you may wish to set this options:

* Binary: `/usr/bin/gnome-terminal` (Note: this path is just a guess, you can get fill path via `which gnome-terminal` command.)
* Arguments: `-e`

How to test:

1. Select any Icon in the Programs tab (winecfg for example)
2. Right click -> Options
3. Navigate to Advanced tab.
4. Select `Run with output to console`
5. Click Ok
6. Run Icon
7. q4wine should run selected wine program using gnome-terminal (you will see a lot of wine's stderr/stdout massages in it)

Let me know if you was able test `gnome-terminal` support so I can update auto detection logic to support it for you.

**Comment by Connor84** [comment]
Some strange things.

1 - I used your binary and argument.  q4 was happy with that.  I tried installing a game that I had previously working via F26 and q4wine.  It installed.  I ran the game (it started in full screen as normal).  Now when I scroll to the outer edge of the screen, it scrolls to the desktop.  This is new.

2 - Then I tried regedit (which was working fine in F27 prior to installing q4wine, and just fine in F26 with q4wine).  Whenever I scroll over a Wine window, the pointer disappears and I am not able to click on anything in the window.  Only the top bar of the window is clickable (and shows the pointer).  I tried uninstalling q4wine, but this issue persisted.

3 - Attempting to follow your instructions, if I right click in my menu on any item (including winecfg), there is: Add to panel, Add to desktop, Add to favorites.  No advanced tab.

**Comment by tehnick** [comment]
Do you use XOrg and Wayland sessions of GNOME in F26 and in F27?

**Comment by Connor84** [comment]
I don't know what that means.  I checked dfndragora and it seems that both XOrg and Wayland are installed.  I don't know what these are and if one or both are running.

**Comment by brezerk** [comment]
Hi @Connor84 

not sure about 1 and 2 issues -- this seems to be related to wine and F27 itself.
Are you able to reproduce this issues w/o q4wine installed and fresh wine prefix?

As for 3: this steps needs to be done via the q4wine gui:

1. Select any Icon in the Programs tab (winecfg for example)
2. Right click -> Options
![image](https://user-images.githubusercontent.com/23820/33527394-ad544792-d858-11e7-879b-d49cd97e8f60.png)
3. Navigate to Advanced tab.
4. Select Run with output to console
5. Click Ok
![image](https://user-images.githubusercontent.com/23820/33527399-c7fe77c0-d858-11e7-9042-fcb00ce2cffa.png)
6. Run Icon
7. q4wine should run selected wine program using gnome-terminal (you will see a lot of wine's stderr/stdout massages in it)
![image](https://user-images.githubusercontent.com/23820/33527404-e971f0bc-d858-11e7-8f58-8e251353ad2d.png)

**Comment by Connor84** [comment]
I do not know how to get to the screen in your step 2.  I tried launching the 13 items in my q4wine submenu and none of them show a screen like that one.

![screenshot from 2017-12-03 23-49-31](https://user-images.githubusercontent.com/33960967/33538051-c8baa040-d884-11e7-8faf-f46f0ab5368e.png)

**Comment by Connor84** [comment]
Installing an app via q4wine opened up the gui.  So I was able to follow your instructions.  (I don't know why there would not be a q4wine gui option in the start menu.)  Here is the output:

fixme:winediag:start_process Wine Staging 2.20 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.

**Comment by brezerk** [comment]
Thank you so much for testing and reporting.

Terminal detection logic has been updated to support `gnome-terminal`  https://github.com/brezerk/q4wine/commit/427cec5b6cd4fcfee7b09614033f7e622606c100

As for q4wine gui option: this seems to be strange for me too.
Can you confirm you have `/usr/share/applications/q4wine.desktop` file installed on your system?

**Comment by Connor84** [comment]
/usr/share/applications/q4wine.desktop is present

**Comment by brezerk** [comment]
Thanks for confirmation.

q4wine.desktop file is a standard for applications to integrate into a desktop environment. as long as it is present, your desktop environment should pick it up and show in the applications menu.

If you see no q4wine gui entity in the applications menu -- this is most likely to be a bug of your current desktop environment.
