### ISSUE TITLE
Qt5?

### ISSUE THREAD

**Issue by romulasry** [brezerk/q4wine#119]
Is qt5wine in the works?

**Comment by tehnick** [comment]
> Is qt5wine in the works?

LOL. q4wine is "Q for WINE". It is not related to Qt version.
As for build with Qt 5.x: just read [INSTALL](https://github.com/brezerk/q4wine/blob/master/INSTALL) file.

**Comment by brezerk** [comment]
Hi @romulasry 

q4wine supports qt5 builds starting from v1.2-r1. for v1.3.6+ it is enabled by default.
If you are building q4wine from the sources -- see QT5 in the INSTALL file.
