### ISSUE TITLE
gui_sudo missing in Ubuntu 18.04

### ISSUE THREAD

**Issue by Eonfge** [brezerk/q4wine#120]
Bit of background:
gksu and all the likes have been deprecated for some time. It started live as a hack to get GUI Tools while using Root privileges but it has become more then is healthy. That is over now, gksu is now officially gone from Ubuntu 18.04. 

q4wine can't deal with it:

> Error while loading application settings by key: 'gui_sudo'. File or path does not exist: "/usr/bin/gksudo"
> Please, go to the q4wine options dialog and set it.

Honestly, q4wine should be changed so that it uses the pkexec standard:
https://www.freedesktop.org/software/polkit/docs/0.105/pkexec.1.html

That means that _$ gksudo nautilus /file_ becomes _$ nautilus admin///file_ and that Nautilus knows that it must open a file for which it should also secure root privileges.

More details:
https://itsfoss.com/gksu-replacement-ubuntu/

proposed triage: Remove the setting and inputfield for now. That makes it possible again to configure the application, because as of now the application can't be properly configured.

**Comment by brezerk** [comment]
Thanks for info. Will take a look on it.

**Comment by brezerk** [comment]
hi @Eonfge 

https://github.com/brezerk/q4wine/commit/8decbb3b6a21cdc45f03b5be96138b186aaf4e0c implements support for pkexec standard. it also should take care of 'Error while loading application settings by key: 'gui_sudo'. File or path does not exist: "/usr/bin/gksudo"' error gracefully.

**Comment by Eonfge** [comment]
I'm connected to the PPA; http://ppa.launchpad.net/tehnick/q4wine/ubuntu/dists/ But Bionic is not yet available. I'll keep an eye out for further bugs if I find them.

**Comment by brezerk** [comment]
hi @Eonfge 
Can we close this ticket?

**Comment by brezerk** [comment]
Closing old ticket as a part of pre-release maintenance. Feel free to reopen if needed.
