### ISSUE TITLE
How to export argument before to launch the applications ?

### ISSUE THREAD

**Issue by berillions** [brezerk/q4wine#127]
Hello,
I use Wine + DXVK to launch Directx11 games with Vulkan.

Before to launch the game with q4wine, i need to export some functions like that : 
`export DXVK_FAKE_DX10_SUPPORT=1
export DXVK_HUD=1
export DXVK_DEBUG_LAYERS=0
export DXVK_LOG_LEVEL=none
export DXVK_USE_PIPECOMPILER=1`

I created a script and added it in "Options-Scripts-PreRun" but i don't know why, the script is not launched before the game...

**Comment by brezerk** [comment]
Hi @berillions 

Pre run will not help you to solve the problem. Pre run scripts are running in separate process and any exports defined will not take any effect on wine application itself.

You have two options:

1. Define required export in you bash profile i.e. `.bashrc` or `.bash_profile` (See: http://mywiki.wooledge.org/DotFiles). This will set this environment variable on on a user level. 

2. Q4Wine allows user to redefine execution string on Prefix level: https://q4wine.brezblock.org.ua/documentation/en_us/10-prefix-settings.html#advanced You can modify default template to include any required variables.
