### ISSUE TITLE
custom virtual desktop resolution [feature request]

### ISSUE THREAD

**Issue by tebicap** [brezerk/q4wine#131]
It would be useful to have a way to specify custom desktop resolutions in runtime.

**Comment by brezerk** [comment]
Hi @tebicap 

Following commits should implement requested feature:

51d0cb9c1aaadbe16a289e3b60404140ed96c97e
de540df9c5ca48ba8bee0b42efc24fcc1b4f36c4
574d1392f6eae98009b1f6c0562d961b2f8d27d7

This a still cmbo boxes, but you should be able to edit the value:
![image](https://user-images.githubusercontent.com/23820/44925985-ad3d4080-ad58-11e8-8b9e-76ecfa155e8b.png)

Please test and let me know in case of any issues.

Thanks for the feature request.

**Comment by tebicap** [comment]
Thanks brezerk!
