### ISSUE TITLE
q5wine

### ISSUE THREAD

**Issue by necrose99** [brezerk/q4wine#137]
https://www.kdab.com/automated-porting-from-qt-4-to-qt-5/
https://github.com/KDAB/Qt4to5
gentoo has axed q4wine as nost Linux's incuding debian look to drop qt4 support.

**Comment by tehnick** [comment]
Read the q4wine documentation. Also I would recommend you to look at q4wine package in Debian...

**Comment by tehnick** [comment]
q4wine name is not at all related to Qt 4.x. It is "Q For WINE".
And program was ported to Qt 5.x very very long time ago...

**Comment by brezerk** [comment]
@necrose99 jfyi: Gentoo didn't axed anything. They are bit slow on bumping ebuilds versions https://bugs.gentoo.org/665708 (Open since 2018-09-11)
