### ISSUE TITLE
[Bug] Display of Valve Proton in Processes view

### ISSUE THREAD

**Issue by Eonfge** [brezerk/q4wine#138]
Currently, Q4Wine has partial for Valve Proton processes in it's system. It would be useful if something was done with this in a more constructive manner. See the image:

![screenshot from 2018-09-23 11-25-51](https://user-images.githubusercontent.com/33983090/45926536-bf5b6a80-bf23-11e8-8800-7b05b356eec9.png)

There are roughly two options: 

- Hide all Proton processes (The ones without a prefix path)
- Flag the processes as Proton processes

**Comment by brezerk** [comment]
Thank you for the bug report. I'll take a look on it.

**Comment by brezerk** [comment]
from what i see Proton is expiring the  WINEPREFIX variable:

```
WINEPREFIX=/home/brezerk/.local/share/Steam/steamapps/compatdata/214730/pfx/
```

this is good

**Comment by brezerk** [comment]
in order to control the process, you have to supply all variables like:

```
 WINEDLLPATH=/home/brezerk/.local/share/Steam/steamapps/common/Proton\ 3.7/dist/lib64/wine WINEPREFIX=/home/brezerk/.local/share/Steam/steamapps/compatdata/214730/pfx/ WINEESYNC=1 /home/brezerk/.local/share/Steam/steamapps/common/Proton\ 3.7/dist/bin/wineserver -k
```

**Comment by brezerk** [comment]
So here is the issue:

Currently q4wine relays on the information present in the q4wine db regarding the wineprefix information:

```
            execObj.cmdargs = "-kill";
            execObj.execcmd = "wineserver";

            if (!this->runWineBinary(execObj, db_prefix.getName(prefix_path), false)){
                return false;
            }
```
I think it is not the best solution: since you can have such side-running process in general (not really related to Proton). So I guess I need to change logic a bit: we need to extract the environment variables for the process.

**Comment by brezerk** [comment]
as for the process list. this commit will fix the process display: https://github.com/brezerk/q4wine/commit/7bfd03ff6c14e58fcadb57f99c4b7eada96a6c66 you will be able to control single process via 'Stop current' and 'Renice'. The 'Stop wine' action will require additional fix.

![image](https://user-images.githubusercontent.com/23820/46131706-fd6ace00-c244-11e8-8be9-97b99fcc75d1.png)

**Comment by brezerk** [comment]
This one https://github.com/brezerk/q4wine/commit/7ef9192e4aa84387b8de9745fd7a8d2f59dfe7f4 will address the 'Stop wine' action.

Should be all set now. Test please and reopen if needed.

Thanks.
