### ISSUE TITLE
Error: wrong or broken XML data. 

### ISSUE THREAD

**Issue by tigerjack** [brezerk/q4wine#146]
The issue is identical to https://github.com/brezerk/q4wine/issues/132 and https://github.com/brezerk/q4wine/issues/114, so not too much to add. I'm using 1.3.10 on ArchLinux.

**Comment by brezerk** [comment]
Yeah. I am installing new hw and upgrading current software on the hosting site. It will become available in couple days (probably by the end of the week or sooner);

**Comment by brezerk** [comment]
I think you should be able to query appdb now.
The only issue you will get 'Error: wrong or broken XML data.' at the beggiging but it will load the data after few seconds.
The reason: I'am enforcing SSL connection now, so https scheme needs to be set for application as well.

**Comment by brezerk** [comment]
Okay. I have updated application code to use SSL Scheme by default too. You may build new version or wait for next release.

Thanks for bringing my attention on this.

Reopen if needed.
