### ISSUE TITLE
Fedora package falling behind

### ISSUE THREAD

**Issue by Eonfge** [brezerk/q4wine#148]
Hey, I found that the current Fedora package is not up to date. Fedora is currently running 1.3.6 which is a same because the latest release is 1.3.11

**details**
https://apps.fedoraproject.org/packages/q4wine
https://fedora.pkgs.org/30/fedora-x86_64/q4wine-1.3.6-5.fc30.x86_64.rpm.html

**Cause**
It looks like the package maintainer is gone, he also isn't replying to messages concerning missing AppData:
https://bugzilla.redhat.com/show_bug.cgi?id=1476492

**Possible workaround**
https://software.opensuse.org/package/q4wine?search_term=q4wine
SUSE Tumbleweed comes with an RPM package, containing 1.3.11

Never mind, workaround won't work
```
['\n Problem: conflicting requests\n - nothing provides fuseiso needed by q4wine-1.3.11-1.5.x86_64\n - nothing provides libQt5Core.so.5(Qt_5.13)(64bit) needed by q4wine-1.3.11-1.5.x86_64']
```

fuseiso could be installed from RPM Sphere, but libQt5Core is not packages as such for Fedora.

**Comment by brezerk** [comment]
hi @Eonfge 

I would assume libQt5Core.so should be provided by https://apps.fedoraproject.org/packages/qt5-qtbase at least i do see it in the qt5-qtbase-5.X.rpm :)

fuseiso is optional, but quite useful if you are planning to mount any iso images. 

As for AppData issue -- not sure what exactly do you need. This seems to be Distro-specific.

**Comment by Eonfge** [comment]
Uhm, looking at #147, I think it's better to let this issue rest for the time being. If you're able to publish a Flatpak version to Flathub, then there will be no more need for an independent Fedora branch.

The AppData is a file like this:
https://github.com/flathub/com.skype.Client/blob/master/com.skype.Client.appdata.xml

It's a file that is required for GNOME Software and KDE Dolphin to know what is up. it gives info on version numbers, content ratings and more.

**Comment by tim77** [comment]
Filed a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1826866).

[Non-responsive maintainer policy](https://docs.fedoraproject.org/en-US/fesco/Policy_for_nonresponsive_package_maintainers/).

**Comment by Eonfge** [comment]
@tim77 Thank you very much. I was not aware that there was such a page. I even created a reddit post last week about this problem:
https://www.reddit.com/r/Fedora/comments/g2lbji/how_to_agenda_an_outdated_package/

**Comment by dkryzhevich** [comment]
Fedora will get 1.3.12 in a week (it's a standart update procedure). It is in testing repo now.

Thanks for contact me directly, you know.

**Comment by Eonfge** [comment]
@dkryzhevich I'm not really connected to the whole Fedora packaging system. See it from my perspective. Where should I have started? @tim77 posted some procedures yesterday, but until then I had no idea how to do this properly.

Thanks for doing it, but don't judge me or @brezerk for not knowing how every distro ecosystem works.

**Comment by tim77** [comment]
> Fedora will get 1.3.12 in a week (it's a standart update procedure). It is in testing repo now.

[Where](https://bodhi.fedoraproject.org/updates/?packages=q4wine) is update for F32? And not need to wait for a week, give a karma for update and Bodhi will push it into Stable repo. [How to test updates](https://fedoramagazine.org/contributing-fedora-testing-packages/).

> Thanks for contact me directly, you know.

Nothing happens when someone contacted you directly until unresponsive procedure was started. This is not personal or something. Your last update of `q4wine` was in 2017. If you have no time to maintain it you should orphan it.

**Comment by dkryzhevich** [comment]
> Where is update for F32?
Here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-563099884c
> give a karma
Yeah, three at least. I had never got so much for my updates so didn't mention. You need FAS account to vote.
Anyway, karma appreciated even if it will be below threshold.
> Nothing happens when someone contacted you directly until unresponsive procedure was started. 
What. Latest rhbz report was closed as FIXED (ok, currentrelease what is the same). See latest reply from  AsciiWolf.

**Comment by tim77** [comment]
> Here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-563099884c

Don't say like it was exist before until i ask you.

> Yeah, three at least. I had never got so much for my updates so didn't mention.

Not three at least. You can lower it to 1.
