### ISSUE TITLE
[Feature request] Add ability to add custom environment variables

### ISSUE THREAD

**Issue by v1993** [brezerk/q4wine#149]
I want to add some environment variables to some of programs I launch using Q4Wine, but it doesn't seem to be currently possible.

Example of such a need is Cemu emulator, where the following settings are recommended (for Nvidia):

```Bash
__GL_THREADED_OPTIMIZATIONS=1 vblank_mode=0 WINEESYNC=1
```

**Comment by brezerk** [comment]
it is possible to do on prefix level (not per applciation/icon), see: https://q4wine.brezblock.org.ua/documentation/en_us/10-prefix-settings.html#advanced
