### ISSUE TITLE
Winetricks functionality fails to work

### ISSUE THREAD

**Issue by prurigro** [brezerk/q4wine#15]
OS: Archlinux
Arch: x86_64

Notes:
1. I initially ran into this problem while having the winetricks archlinux package installed, which places winetricks in $PATH, however, I uninstalled the package and the problem persists.
2. winetricks does work on its own.
3. Q4Wine was tested in both version 0.121 and the latest git pull, and although they're setup differently, they both fail in a similar fashion. For this bug report I'm using the latest git pull.

To produce error for 'Install or update Winetricks script' option:
1. Start q4wine
2. Click the 'Setup' tab
3. Select 'Winetricks' from the options on the left
4. Double click 'Install or update Winetricks script' on the right
5. GUI does nothing, and CLI output when run in a terminal is: "Failed to parse arguments: Unknown option -c"

To produce error for 'Refresh Winetricks application list' option
1. Start q4wine
2. Click the 'Setup' tab
3. Select 'Winetricks' from the options on the left
4. Double click 'Refresh Winetricks application list' on the right
5. GUI shows the text: "Refresh Winetricks application list" and a progress bar that starts at 5% and never increases, and there is no output CLI output when run in a terminal

I'm guessing the second option doesn't work because the first one was never able to install winetricks, but I included it in the report because it seems like it would be a good idea to deactivate the second option if winetricks isn't available.

Let me know if you need any additional information,

Cheers!

**Comment by Gfurst** [comment]
So whats the deal, nearly 4 years later and I'm having this issue... konsole still wont open due to `unkown option 'c'`

arguments `--noclose -e` I skimmed through the issue, but haven't found why
