### ISSUE TITLE
Generate StartupWMClass values in created .desktop files?

### ISSUE THREAD

**Issue by Chromace** [brezerk/q4wine#153]
Currently, the .desktop files that are generated via Q4Wine do not include a custom StartupWMClass property. This allows for a better distinction of separate applications, allowing desktops to group them in a more relevant way (a link explaining this is [over here](https://bugs.winehq.org/show_bug.cgi?id=32699)).

As such, it would be nice if Q4Wine automatically generated this for its .desktop files - a workaround exists in manually renaming them, but these changes won't last after a modification through Q4Wine. The value of StartupWMClass should be the same as the name of the currently targeted executable, explained in the above link: `StartupWMClass=<name of the exe-file>`

**Comment by brezerk** [comment]
Thank you for the request.

https://github.com/brezerk/q4wine/commit/597677655bf5b6fa167dc3fad73def3060e9d9c3 should add requested filed to exported .desktop file.  

Reopen if needed.
