### ISSUE TITLE
Misspelled Color Theme Settings

### ISSUE THREAD

**Issue by Chromace** [brezerk/q4wine#155]
Currently, some Wine colour settings are misspelled, meaning that they're not applied to the Wine prefix. They are as follows (with the correct spelling to their right):

- ButtonHighlight = ButtonHilight
- Highlight = Hilight
- HighlightText = HilightText
- MenuHighlight = MenuHilight

**Comment by brezerk** [comment]
Thank you. Will take a look.

**Comment by brezerk** [comment]
Should be fixed now: https://github.com/brezerk/q4wine/commit/eebb49528c78f216d3579db3093e4b1f0c44d533

Reopen if need. Thanks!
