### ISSUE TITLE
Need import prefix from the file system

### ISSUE THREAD

**Issue by msdobrescu** [brezerk/q4wine#160]
How can be imported a prefix created outside of Q4Wine?

**Comment by brezerk** [comment]
hi @msdobrescu 

there are two options:
1. create tar bz2 archive and import it via Prefixes -> Import feature.
2. import existing prefix located at ~/.local/share/wineprefixes via Programs -> Import prefixes

**Comment by brezerk** [comment]
Seems to be resolved. Reopen of needed;
