### ISSUE TITLE
Use LC_ALL instead of LANG to force override applciation locale

### ISSUE THREAD

**Issue by rodin-ia** [brezerk/q4wine#165]
Hi, thanks for the program.
There is a problem, I'm working on the en_US.UTF-8 locale, there are problems with encodings in old XP applications. Russian characters are displayed as signs "?", "|". Specifying the LANG parameter in the properties of the shortcut: ru_RU.UTF-8 (via q4wine) does not give any result. If you open the console, set LC_ALL=ru_RU.UTF-8 there, application is normally localized. You can ask to add the ability to specify the value of the LC_ALL variable in the shortcut options. Thanks!

**Comment by brezerk** [comment]
Thanks for reporting. Should be fixed now. Reopen if needed.
