### ISSUE TITLE
Error: wrong or broken XML data. Try again later

### ISSUE THREAD

**Issue by warcayac** [brezerk/q4wine#166]
I recently installed Q4Wine 1.3.12 on Manjaro KDE Plasma (latest version). When trying to list available Wine AppDB I get this message "**Error: wrong or broken XML data. Try again later**", and panel is always in blank.

**Comment by brezerk** [comment]
Thank you.
Seem like an issue after migrating backed to Pythong3.
I'll take a look.

**Comment by brezerk** [comment]
Should be fixed now. 
Reopen if needed.

Thanks!
