### ISSUE TITLE
Request for improvement: List installed apps and options

### ISSUE THREAD

**Issue by warcayac** [brezerk/q4wine#167]
Your app is missing a feature which lists installed apps per prefix, and shows options like: create shortcut in desktop, uninstall, etc.

At present my shortcut was eliminated from Desktop (while installing DLLs in another prefix) and I don't know how to restore that shortcut.

**Comment by brezerk** [comment]
hi @warcayac 

unfortunately this in not something I can implement. 
Windows (and so does Wine) does not have a nor `repository` nor a `package manager` to list installed applications easily.

You can use default Wine `uninstaller` applet available at Q4Wine `system` folder for each prefix.
The other solution is to use 3rd party plugin `winetools` with `list-installed` argument. But it will show only things that has been installed via `winetools` itself and noting else.
