### ISSUE TITLE
[Question] Can you add already existing prefixes?

### ISSUE THREAD

**Issue by Toadfield** [brezerk/q4wine#176]
I wanna know that,cause I wanna add some steam games that need a mod launcher.
And also can I add multiple prefixes at once if that works?

**Comment by brezerk** [comment]
hi @Toadfield 
yes, you can.

q4wine allows you to import prefixes created under `${HOME}/.local/share/wineprefixes` in one shot via Import action available at Programs tab.

If you would like to import prefixes from the other directory: it is not possible atm. As a workaround you can symlink `${HOME}/.local/share/wineprefixes` to a top level directory. Or symlink existing prefixes into `${HOME}/.local/share/wineprefixes` 

Alternatively, you can create prefix and just point prefix path to an existing wine prefix directory. q4wine won't remove anything unless asked explicitly.

**Comment by Toadfield** [comment]
Can I change where the default prefixes are located?
But then I have the problem that I couldn't add steam game prefixes and stuff like that.

**Comment by brezerk** [comment]
> Can I change where the default prefixes are located?

Yes, you can: File -> Options -> Advanced -> Default directory for new wine prefixes;

> But then I have the problem that I couldn't add steam game prefixes and stuff like that.

Why? You still should be able to create prefixes using existing fake steam drive and setup wine versions to point to proton binaries I think.

**Comment by brezerk** [comment]
Seems like resolved. Reopen if needed.
