### ISSUE TITLE
XDG Base Directory Specification support

### ISSUE THREAD

**Issue by tim77** [brezerk/q4wine#178]
Hello. Currently `~/.config` and `~/.local/share` paths are hardcoded in the app. The problem is that non-compliance with the XDG standard doesn't allow to control the location of data/configurations when using environment variables `XDG_DATA_HOME/XDG_CONFIG_HOME` as prescribed by the specification.

This especially important for packaging app in Flatpak format. This is must have for solving this issue https://github.com/brezerk/q4wine/issues/147#.

See:
- https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
- https://doc.qt.io/qt-5/qstandardpaths.html

**Comment by brezerk** [comment]
Yeah. This is quite good legacy. Looking

**Comment by brezerk** [comment]
Thanks for reporting; Should be resolved now.

**Comment by tim77** [comment]
Just awesome. @brezerk thanks a lot. I've already tested a little bit this patches and LGTM.
