### ISSUE TITLE
[Question] Can I open programs with programs that are added to q4wine?

### ISSUE THREAD

**Issue by Toadfield** [brezerk/q4wine#183]
I want to open files with windows programs that are added to q4wine.

**Comment by brezerk** [comment]
Hi @Toadfield 

sry, somehow I missed your request :|

yes, you can: you need to associate desired mime type with q4wine-cli:

here is an example to open .sh file with notepad: 
```
q4wine-cli -p Default -d system -i wordpad ~/develop/conky.sh
```

see: man q4wine-cli for details

**Comment by brezerk** [comment]
Seems like resolved. Reopen if needed.
