### ISSUE TITLE
Installing stuff with winetricks

### ISSUE THREAD

**Issue by mobedoor** [brezerk/q4wine#186]
Hello.
![Screenshot_2021-05-15_20-17-13](https://user-images.githubusercontent.com/71059800/118368074-b16a2480-b5ba-11eb-9a12-9e28148bb2a1.png)
I cannot install stuff with winetricks. In [screenshots](https://www.maketecheasier.com/assets/uploads/2012/11/q4wine-winetricks-installmspaint.png.webp) I saw online for q4wine I can see an install button which is not displayed for me.

Any help would be appreciated.
q4wine 1.3.11

**Comment by mobedoor** [comment]
Issue fixed after setting konsole as the terminal. I was using my system's default.

**Comment by brezerk** [comment]
@mobedoor just curious: what was your system's default terminal?

**Comment by mobedoor** [comment]
xfce4-terminal

**Comment by brezerk** [comment]
you may wish try to set it back and make sure you specify `-e` argument. let me know if it works

**Comment by mobedoor** [comment]
That did it. Thanks a lot.
