### ISSUE TITLE
When I try to install the winetricks script from the q4wine package, I get the error 'Warning: The interactive shell could not be found.'

### ISSUE THREAD

**Issue by saber716rus** [brezerk/q4wine#187]
The program is installed from aur. https://aur.archlinux.org/packages/q4wine
The problem is that when I try to install winetricks from the program or install lib, so from the program, I come across such an error. "Warning: The interactive shell could not be found."
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.10.42-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 6 × AMD FX(tm)-6300 Six-Core Processor
Memory: 7.7 ГиБ of RAM
Graphics Processor: GeForce GT 630/PCIe/SSE2

**Comment by brezerk** [comment]
hi @saber716rus 

You may need to check console binary setting at q4wine settings : General -> Utils 

More likely this could be b/c missing or wrong binary path

**Comment by saber716rus** [comment]
![Screenshot_20210708_143629](https://user-images.githubusercontent.com/22714555/124915192-eebac380-dff9-11eb-94e2-905cd0bc230b.jpg)
As you can see, there is a working terminal and everything is correct at the address. The system is installed on ssd and mounted f2fs.

**Comment by 10v33r** [comment]
Hi,
Sorry for bumping this thread.
I'm having the exact same issues on Manjaro Linux.

![Screenshot_20210709_001927](https://user-images.githubusercontent.com/67891215/124972227-eab79180-e04b-11eb-932b-47a1645b419c.png)
![Screenshot_20210709_001927](https://user-images.githubusercontent.com/67891215/124972240-ee4b1880-e04b-11eb-8b6b-f231b71bbcc8.png)

**System info**
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.10.42-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × AMD Ryzen 5 2400G with Radeon Vega Graphics
Memory: 5.8 GiB of RAM
Graphics Processor: AMD Radeon™ Vega 11 Graphics

**Comment by brezerk** [comment]
hm....
interesting... i can't reproduce this on my system.
can you build q4wine with DEBUG option enabled and add console output?

on my system it runs winetricks as follows:
```
[DD] winetricks args:  ("--noclose", "-e", "/bin/sh", "-c", "env WINEPREFIX='/home/brezerk/.wine' WINE='/usr/bin/wine' WINELOADER='/usr/bin/wine' WINESERVER='/usr/bin/wineserver' /usr/bin/sh -c \"/home/brezerk/.config/q4wine/winetricks --no-isolate 7zip\" ; echo '== Press Enter to Close =='; read n")
```

**Comment by brezerk** [comment]
seems like in your case the issue with '/bin/sh' part. What is the value for `sh` setting in General -> System?

**Comment by saber716rus** [comment]
> seems like in your case the issue with '/bin/sh' part. What is the value for `sh` setting in General -> System?

shell zsh

**Comment by saber716rus** [comment]
`[nikolanp@kolyab-tobefilledbyoem ~]$ q4wine
[ii] Loading translation:  "q4wine_ru_RU"
qt.svg: <input>:7064: Could not resolve property: #radialGradient3709
qt.svg: <input>:647:190: Could not resolve property: #linearGradient5167
qt.svg: <input>:647:190: Could not resolve property: #linearGradient5167
qt.svg: <input>:6354: Could not resolve property: #linearGradient5167
qt.svg: <input>:6354: Could not resolve property: #linearGradient5167
qt.svg: <input>:5672: Could not resolve property: #radialGradient3709
qt.svg: <input>:647:190: Could not resolve property: #linearGradient5167
qt.svg: <input>:5672: Could not resolve property: #radialGradient3709
qt.svg: <input>:7064: Could not resolve property: #radialGradient3709
qt.svg: <input>:684: Could not resolve property: #pattern5614
qt.svg: <input>:684: Could not resolve property: #pattern5626
qt.svg: <input>:684: Could not resolve property: #pattern5614
qt.svg: <input>:684: Could not resolve property: #pattern5626
qt.svg: <input>:679: Could not resolve property: #pattern5614
qt.svg: <input>:679: Could not resolve property: #pattern5626
qt.svg: <input>:7092: Could not resolve property: #linearGradient3592
qt.svg: <input>:7092: Could not resolve property: #linearGradient7999
qt.svg: <input>:7092: Could not resolve property: #radialGradient2943
qt.svg: <input>:6850: Could not resolve property: #radialGradient2943
qt.svg: <input>:6354: Could not resolve property: #linearGradient5167
qt.svg: <input>:6354: Could not resolve property: #linearGradient5167
qt.svg: <input>:7064: Could not resolve property: #radialGradient3709
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
qt.svg: <input>:4290: Could not resolve property: #pattern5614
qt.svg: <input>:4290: Could not resolve property: #pattern5626
[nikolanp@kolyab-tobefilledbyoem ~]$ `

**Comment by brezerk** [comment]
> shell zsh

@saber716rus ic. can you set it to `sh`? you may find `sh` binary via `which sh`

**Comment by saber716rus** [comment]
Проблема исчезла, но есть просьба, сделайте, чтобы после выполнении скриптов winetricks, должно быть авто закрытие shell окна.

**Comment by saber716rus** [comment]
The problem has disappeared, but there is a request, make sure that after executing the winetricks scripts, the shell window should be auto-closed.

**Comment by brezerk** [comment]
I'll need to take a look why it does not work with `zsh` tho. Are you using any special `.zshrc`?

As for > make sure that after executing the winetricks scripts, the shell window should be auto-closed.

You need to remove `--noclose` from q4wine console settings.
