### ISSUE TITLE
shortcut not be removed after unintall the software

### ISSUE THREAD

**Issue by ss8688** [brezerk/q4wine#196]
Shortcut not be removed after unintall the software，even after unitall the q4wine.
And,I can not find it in `/usr/share/applications`
<img width="480" alt="image" src="https://user-images.githubusercontent.com/59367202/191760653-fa7a4519-6bea-4890-901d-8cd167ca1caa.png">
How could I remove them?
Thanks.

**Comment by brezerk** [comment]
hi @ss8688 

I believe this are created in the personal space i.e. somewhere at `/home/$USER/.local/share/applications/`

**Comment by ss8688** [comment]
Thanks
Those shortcuts have be removed after I upgrade the system.

**Comment by ss8688** [comment]
Thanks
Those shortcuts have be removed after I upgrade the system
