### ISSUE TITLE
Replace default raster icons with SVG analogs

### ISSUE THREAD

**Issue by skybon** [brezerk/q4wine#21]
Vector graphics has lesser size and higher quality. Replacing PNG with SVG would be a progress. Also it is possible to remove icons from q4wine package and add dependency on Nuvola / Oxygen icon themes.

**Comment by tehnick** [comment]
New program icon looks very ugly in with dark Qt themes.
Please add white border or something similar.
Ideally new svg icon should look exactly as old png icon.

**Comment by brezerk** [comment]
Hi @tehnick ,

it does have an light-grey border: 
![icon](https://cloud.githubusercontent.com/assets/23820/12551702/fe3dcfe8-c374-11e5-87f6-85918a489212.png)

I can make it white if you wish so.
Anyway, can you attach an screenshot, please?
Just wonder how it looks on your system :)

**Comment by tehnick** [comment]
![desktop_529](https://cloud.githubusercontent.com/assets/441190/12565465/a05a5f08-c3c5-11e5-8c43-afc5a1b2b833.png)
![desktop_531](https://cloud.githubusercontent.com/assets/441190/12565463/a059aa86-c3c5-11e5-8e3a-e84f3fe923ac.png)
![desktop_532](https://cloud.githubusercontent.com/assets/441190/12565462/a0598560-c3c5-11e5-89e1-7467138b1b12.png)
![desktop_533](https://cloud.githubusercontent.com/assets/441190/12565464/a05a1a34-c3c5-11e5-8552-707d87ce0aed.png)

**Comment by tehnick** [comment]
Debian unstable, Qt 5.5.1, Plasma desktop 5.4.3, KF5 5.16.0
q4wine from master branch vs q4wine-1.1-r2

**Comment by brezerk** [comment]
Can you try it now, please?

**Comment by tehnick** [comment]
![desktop_534](https://cloud.githubusercontent.com/assets/441190/12589697/213f4584-c470-11e5-9e1c-145a6cba9a83.png)
![desktop_535](https://cloud.githubusercontent.com/assets/441190/12589698/213fe3ea-c470-11e5-9f28-48d04e6a30f4.png)

**Comment by tehnick** [comment]
As you can see the difference in quite small. I propose to use strictly white and opaque border. Inkscape shows me that now it is transparent for 80%.

**Comment by tehnick** [comment]
Also I have to note that almost always tiny and small raster icons looks much better than scaled vector icons. For example, previous picture of heart in png variant is much nicer than in scaled vector one.

**Comment by tehnick** [comment]
> I propose to use strictly white and opaque border.

If you agree I can fix it myself.

**Comment by brezerk** [comment]
Hi @tehnick ic. try this one: https://github.com/brezerk/q4wine/commit/f6743745e68392a4c99500ad63767b2ebd78e97e

>If you agree I can fix it myself.

Feel free to fix or play around whatever you wish to.

**Comment by tehnick** [comment]
![desktop_536](https://cloud.githubusercontent.com/assets/441190/12598395/2495ae5a-c49b-11e5-9790-67935c9d48df.png)
![desktop_537](https://cloud.githubusercontent.com/assets/441190/12598394/2495410e-c49b-11e5-80bb-f78deead7802.png)

**Comment by tehnick** [comment]
Теперь гораздо лучше и баг можно считать исправленным.

По моему мнению, все градиенты из иконки лучше убрать, сделав ее плоской и контрастной. Толщину ножки бокала в самом узком месте желательно увеличить, а верхние углы скруглить. Ну и толщину белой границы можно увеличить. =) Но это уже дело вкуса и к данной задаче не относится.

**Comment by tehnick** [comment]
Для иллюстрации своей идеи добавил пример плоской иконки: 7363ba6

Я не дизайнер и с векторными изображениями имею дело редко, поэтому просьба сильно не придираться... =)

**Comment by tehnick** [comment]
![desktop_539](https://cloud.githubusercontent.com/assets/441190/12599267/8e381a0e-c4a1-11e5-8aa3-09d5669b4d82.png)

**Comment by brezerk** [comment]
Та яж тоже не дизайнер, лол :)
да, без градиента лучше смотрится на мелких размерах, q4wine-flat очень ок.

**Comment by LazyKent** [comment]
А не забыли ли вы, джентльмены, про монохромные иконки?
Как бы не хотелось об этом говорить (и видеть), но возникают такие требования: https://developer.gnome.org/hig/stable/icons-and-artwork.html.ru
Да и KDE, похоже, к этому склоняется.
Конкретно, в системном лотке стало модно показывать монохромный значок.

**Comment by tehnick** [comment]
Есть такая мода, да. Но лично я с ней не согласен.

А что касается иконок на "кнопках", то в сборках программы из мастер-ветки уже используются системные иконки. Как минимум в KDE это работает. Что видно по скриншотам выше.

**Comment by brezerk** [comment]
@LazyKent в комплекте идет и устанавливается q4wine-ambiance.svg он монохромный.
наверно стоит добавить опцию в настройках, которая позволит пользователю переключать значок программы на желаемый.

ps: и да, интересно, как подхват системных иконок работает в других ДЕ (:

pps: @tehnick я поправил то, что ты просил в жаббире.

**Comment by LazyKent** [comment]
@brezerk
Использую Xfce. Протестирую, если скажешь, что нужно попробовать и как.

**Comment by tehnick** [comment]
@brezerk
Если возражений нет, предлагаю иконку с градиентами вообще убрать и поставить вместо нее плоскую.

Что касается монохромной иконки в системном трее, то опция была бы хорошим вариантом.

И еще стало интересно, есть ли какой-нибудь более-менее универсальный (не зависящий от DE) метод автоматического определения того, что пользователь выбрал использование монохромных иконок в настройках своего DE.

**Comment by brezerk** [comment]
@tehnick да, убирай. опцию запилю на недельке.

@LazyKent просто запустить q4wine и посмотреть отличается ли иконки в программе от системных. скорее всего, потребуется какой-то пакет совместимости gtk<->qt4 или gtk<->qt5 на подобии kde-plasma/kde-gtk-config (см: https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications)

@tehnick увы, стандарт (http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) не описывает, как и где должны хранится сами настройки текущей  темы, каждая ДЕ пилит свой ни с чем не совместимый велосипед. В итоге народ пилит костыли для каждого способа хранения, что-то типа этого: https://sourceforge.net/p/doublecmd/code/HEAD/tree/trunk/src/platform/unix/uunixicontheme.pas

В qt есть стандартный метод: http://doc.qt.io/qt-5/qicon.html#fromTheme но оно берет настройки из самого qt, т.е. без прослойки совместимости, сиравно никак :)

**Comment by brezerk** [comment]
добвил опцию. вроде даже работает.

**Comment by tehnick** [comment]
1.2-r2 vs 1.2-r2-54-g5e03363
![desktop_552](https://cloud.githubusercontent.com/assets/441190/13126646/6664cfbc-d5dc-11e5-9d9a-edf2dcbbd9a3.png)
![desktop_540](https://cloud.githubusercontent.com/assets/441190/13126671/7c8489e0-d5dc-11e5-896f-daeba2ec16fc.png)

**Comment by brezerk** [comment]
Thanks, should be fixed with: https://github.com/brezerk/q4wine/commit/d8fba6106300763a1b601553f92ffc0459a3ee6e

Reopen if needed.
