### ISSUE TITLE
Use icons from the system icon theme where possible

### ISSUE THREAD

**Issue by skybon** [brezerk/q4wine#22]
It would be wise not to duplicate Nuvola and Oxygen icons but rather add dependency on these themes. The latter do not depend on GTK+ or kdelibs.

**Comment by brezerk** [comment]
Basic implementation: https://github.com/brezerk/q4wine/commit/c71564aaa35c965173218e0dfd5b992f000e71a4 
Works for KDE4/5. Any issues with compatibility with other DE should be tracked in separate ticket.
