### ISSUE TITLE
configure multiple wine paths globally to allow easily selection in prefixes

### ISSUE THREAD

**Issue by bfx81** [brezerk/q4wine#23]
It's common practise to tie a particular games/application to a specified wine version. Sometimes find the right configuration it's a very time consuming task. 
Q4Wine really helps having all you need under your fingers, but when you need to try different wine versions you have to manually update 4 paths.

I think that could be very useful if the user can configure these paths once grouping them in a "name/version" of his choice. In this way a prefix can select a specific wine version simply selecting it from a list.

I hope this suggestion could be useful for all user of this tremendous useful app!
Tnx in advance.
Fabio

**Comment by ProfessorKaos64** [comment]
Sorry to necro bump, but while it's nice to setup the versions in the wine manager, I don't see why the application can't reach out to WineHQ and download the binary, put it in a  directory, etc.
