### ISSUE TITLE
virtual desktop resolution

### ISSUE THREAD

**Issue by nicknill** [brezerk/q4wine#35]
Please, add new resolution to virtual desktop settings. 
2560x1440 for now is more popular than 2560x1600 (as i think)

Thank you!

**Comment by tebicap** [comment]
Hi, is it possible to add manually virtual desktop resolutions??

**Comment by brezerk** [comment]
hi @tebicap 

well... if by 'manually' you mean patching the code manually -- then, yes ;) but if you think you need ability to specify desktop resolutions in runtime -- please create a new issue.

**Comment by tebicap** [comment]
I was referring to the second one. I created the issue. thanks brezerk
