### ISSUE TITLE
Support for KSNI/AppIndicators

### ISSUE THREAD

**Issue by sl1pkn07** [brezerk/q4wine#52]
Hi

in Plasma-next/KF5 (Qt5) change the method to handle show icon in systray bar

see http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/

greetings

**Comment by skybon** [comment]
You should be able to use QSystemTrayIcon in Plasma Next with Qt 5.4 and later.

**Comment by sl1pkn07** [comment]
I have a Qt 5.4.0 and plasma 5.2.0, does not showing the q4wine systray icon in my desktop

**Comment by skybon** [comment]
Make sure that the icon is enabled in q4wine settings and not hidden in Plasma system tray.

**Comment by sl1pkn07** [comment]
ow men. after close session, now works

sorry


greetings
