### ISSUE TITLE
'Run -> Browser' on Programs window not work 

### ISSUE THREAD

**Issue by sl1pkn07** [brezerk/q4wine#54]
when open the menu (left click) and go to 'Run' -> 'browser' the Run window dont work (nothig happend)

in the console says:

    QSqlQuery::value: not positioned on a valid record

Ctl+Z or 'File' -> 'Run' works ok

greetings

e53bf788c94a720a235d01bde03c1fbf556f0637 build with Qt5 5.4.1

**Comment by skybon** [comment]
Thank you for your bug report.

Cannot reproduce the issue. Could you please provide a screencast of the bug occurence? Thanks.

**Comment by sl1pkn07** [comment]
http://sl1pkn07.wtf/grabacion6.mp4

**Comment by brezerk** [comment]
Reproduced:
```
corelib::getMountedImages( "/mnt/cdrom" )
QSqlQuery::value: not positioned on a valid record
[ee] db_last_run_icon.getByExec return an enpty result
```

**Comment by brezerk** [comment]
Fixed: https://github.com/brezerk/q4wine/commit/3592b5583d1683eb2dd8fc29b9896d612bc363c0

Reopen if needed :)

**Comment by sl1pkn07** [comment]
still here

**Comment by brezerk** [comment]
Argh.. Can you try this fix https://github.com/brezerk/q4wine/commit/d4316d003b346166cfd836c32cd67f5bd4edda73 ?

**Comment by sl1pkn07** [comment]
yes. now works!

tnx bro :)

**Comment by brezerk** [comment]
ur'wecome. thank you for the bug reports and fix testing :)
