### ISSUE TITLE
Using q4wine and Mumble's overlay

### ISSUE THREAD

**Issue by Xylemon** [brezerk/q4wine#56]
I was wondering if it's possible to have the mumble-overlay run with the desktop file you created for the program under q4wine? I've tried messing with the Pre and Post run scripts but no luck.

**Comment by brezerk** [comment]
Hi. If you need to extend wine execution command, then you should use 'Execution Template string'.

Try to play around: Prefix -> Settings -> Advanced -> Execution Template string

I guess for mumble-overlay you should use something like:

%CONSOLE_BIN% %CONSOLE_ARGS% %ENV_BIN% %ENV_ARGS% /bin/sh -c "%WORK_DIR% %SET_NICE% mumble-overlay %WINE_BIN% %VIRTUAL_DESKTOP% %PROGRAM_BIN% %PROGRAM_ARGS% 2>&1 "

or

%CONSOLE_BIN% %CONSOLE_ARGS% %ENV_BIN% %ENV_ARGS% /bin/sh -c "%WORK_DIR% %SET_NICE% LD_PRELOAD=/path/to/libmumble.so.1.1 %WINE_BIN% %VIRTUAL_DESKTOP% %PROGRAM_BIN% %PROGRAM_ARGS% 2>&1 "

**Comment by Xylemon** [comment]
That worked perfectly! Thanks.
