### ISSUE TITLE
add custom dll overrides outside from the list

### ISSUE THREAD

**Issue by sl1pkn07** [brezerk/q4wine#60]
Q4wine can select dll overrides from a list. but can't add a custom library not included in that list

please add support add custom dll library override

**Comment by brezerk** [comment]
Hi @sl1pkn07 ,

custom dll library override added https://github.com/brezerk/q4wine/commit/34c627f8fdd55816ff04af47e57d703b42646177

I also added ability to edit configured overrides. 

Feel free to repoen if the fix does not met your requirements.
