### ISSUE TITLE
Revert "Kill dead online components" breaks the Qt5 build

### ISSUE THREAD

**Issue by sl1pkn07** [brezerk/q4wine#62]
Hi (and Merry Chrismas)

the commit c9e3caeb5be7672f2c4861be352ba35f2158a7d5 break the build with Qt5

-DWITH_WINEAPPDB=OFF can't help

    In file included from /tmp/makepkg/q4wine-git/src/q4wine/src/core/httpcore.cpp:19:0:
    /tmp/makepkg/q4wine-git/src/q4wine/src/core/httpcore.h:27:17: fatal error: QHttp: No such file or directory
    compilation terminated.
    src/q4wine-gui/CMakeFiles/q4wine.dir/build.make:647: recipe for target 'src/q4wine-gui/CMakeFiles/q4wine.dir/__/core/httpcore.cpp.o' failed
    make[2]: *** [src/q4wine-gui/CMakeFiles/q4wine.dir/__/core/httpcore.cpp.o] Error 1

greetings

**Comment by brezerk** [comment]
Merry Chrismas! :)

Yeah.  It seems for QT5 we should use QNetworkAccessManager instead. Will look into it.

**Comment by brezerk** [comment]
There are two issues:

1. Use QNetworkAccessManager instead of QHttp: fixed by https://github.com/brezerk/q4wine/commit/fdf9a15e90167c56212e932bf23d0f75431f117d

2. Do not try to build wineappdb's dependencies in case of '-DWITH_WINEAPPDB=OFF' will be fixed lately.

**Comment by brezerk** [comment]
second issue is fixed too: https://github.com/brezerk/q4wine/commit/ea45aa175f013e75b8912fc6e7f9e1ed7064a236

reopen if needed. tanks for the report and have a nice weekend.

**Comment by sl1pkn07** [comment]
thanks a lot. now builds all ok

have you a great weekend (and rest of chrismas) too
