### ISSUE TITLE
Сайт проекта заблокирован для российских IP

### ISSUE THREAD

**Issue by skybon** [brezerk/q4wine#63]
Алексей, давай на частоту.

Двое из трёх активных контрибьюторов в твой проект живут в России. Мы не причастны ни к каким замутам политиков России и Украины. Не знаю как Борису, но мне твой шаг с блокировкой сайта видится плевком в лицо.

Если ты желаешь вносить полит. треш в проект, то делай это, пожалуйста, без меня - забери моё право на коммиты и удали упоминание из списка разработчиков. Если же тебе не наплевать, то прошу прекратить этот цирк и оставить войну для съедение фейсбук-варриорам.

**Comment by brezerk** [comment]
Артем, не драматизируй, пожалуйста.

У Вас всегда есть возможность поменять страну. Ну или в худшем случае просто обойти это смешное ограничение используя proxy, vpn, tor, whatever. Не вижу никакой проблемы.

Ни сайт, ни его движок, ни тем более его контент никогда не был открытой частью q4wine. И лично Вашего вклада в него нет. Мне очень жаль, но у меня нет желания обслуживать доступ к контенту с территории рф, о чем и сказано на странице. (можешь считать, что мне это запрещают молодчики из правого сектора, если это как-то поможет).

**Comment by skybon** [comment]
Алексей, сайт имеет непосредственное отношение к проекту. Особенно с учётом того, что ты сделал откат моего патча, удаляющего ссылки на сайт, которые в каждой первой менюшке.

Я доволен своей страной и как перчатки менять её не собираюсь, особенно ради человека с майданом головного мозга. Поэтому повторю свою просьбу убрать моё имя из списка разработчиков и снять регалии контрибьютора.

**Comment by brezerk** [comment]
Не подменяй понятия. Сайт, это сайт. q4wine это q4wine. Оба могут и существуют параллельно вне зависимости от ссылок друг на друга. Как следствие права и привилегии распространяющиеся на q4wine не распространяются на сайт. Как и наоборот. 

>с майданом головного мозга

И кто в проект несет политику-то? Не сдерживай себя, давай уже про фашистов, распятых дидов-витиранов в трусиках, и прочее пропагандистское говно, тебе же хочется.

>убрать моё имя

Коммит права у тебя никто не отбирал, будь мужиком, сделай это сам. Мне некогда играть в игры обиженок.

**Comment by q4wine** [comment]
This issue will be remediated with independent fork https://github.com/q4wine/q4wine . Documentation will be stored on github pages, to avoid any personal implications: http://q4wine.org. Previous contributors were already added to this project with push permissions.

**Comment by skybon** [comment]
Убрал себя из списка разработчиков. Всех участников из России призываю сделать то же самое и больше не иметь дел с майдаунами.

**Comment by msva** [comment]
// tfw оба участника устраивают цирк на ровном месте
