### ISSUE TITLE
Translation collaboration tools

### ISSUE THREAD

**Issue by brezerk** [brezerk/q4wine#66]
Hello.

I am currently looking for a way how to organize and simplify translations process for q4wine.
It looks like it will be good idea to setup translation collaboration tools like: transifex or pootle.
So, what tools or process do you prefer?

Any suggestions or comments will be welcome.

**Comment by ercolinux** [comment]
Hi,

no preference both works well so choose the one you prefer

On 17 January 2016 at 15:44, Alexey S. Malakhov <notifications@github.com>
wrote:

> Hello.
>
> I am currently looking for a way how to organize and simplify translations
> process for q4wine.
> It looks like it will be good idea to setup translation collaboration
> tools like: transifex or pootle.
> So, what tools or process do you prefer?
>
> Any suggestions or comments will be welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brezerk/q4wine/issues/66>.
>



-- 
Freedom is nothing else but a chance to be better.(A.Camus)

**Comment by tehnick** [comment]
Hi,

In EiskaltDC++ and Psi+ project we are successfully using Transifex quite a long time:
https://www.transifex.com/tehnick/eiskaltdcpp/
https://www.transifex.com/tehnick/psi-plus/

Unfortunately, during this time Transifex ceased to be an open-source project. Also there were few huge updates in its Web UI and Web API and personally I think that the current UI is much less convenient than old one. But Transifex is still the most convenient online service for localization from what I have seen.

I haven't tried Pootle yet bacause it should be setup on own server as far as I know. It might be interesting to test how Pootle works, but before suggesting it for other translators.

**Comment by brezerk** [comment]
Ok. 

I decided to play around Pootle:

Here you are: http://i18n.brezblock.org.ua/projects/q4wine/

Any suggestions or comments are welcome :)

**Comment by brezerk** [comment]
Hi

After some experiments and tests. I decided to start using  [Weblate](https://weblate.org/uk/) instead of pootle.

It provides flexible and simple git integration as well as github and google authentication via OAuth2.

Currently this new tool has been deployed and configured. It is available via [i18n.brezblock.org.ua](http://i18n.brezblock.org.ua/) url;

Let me know if any issues.

Thanks.
