### ISSUE TITLE
Process explorer is broken

### ISSUE THREAD

**Issue by tehnick** [brezerk/q4wine#70]
![desktop_553](https://cloud.githubusercontent.com/assets/441190/13202554/ddefc340-d8af-11e5-87d3-ebbb4106a08f.png)

**Comment by tehnick** [comment]
Build from HEAD in master branch, Qt 5.5.1, Debian unstable.

**Comment by brezerk** [comment]
hm... I can't reproduce ![plist](https://cloud.githubusercontent.com/assets/23820/13202716/10638788-d8ad-11e5-9ffd-126fc3bbfb07.png)

Is it Linux or BSD system? What is kernel version?

**Comment by tehnick** [comment]
$ uname -a
Linux Tehnick 4.3.0-1-686-pae #1 SMP Debian 4.3.5-1 (2016-02-06) i686 GNU/Linux

**Comment by tehnick** [comment]
I use systemd as init system if this is important. (Sorry but I don't have time to look at q4wine sources now.)

**Comment by brezerk** [comment]
ic. I was not using systemd yet. 

I have added some debug entries to help to track the problem. Can you compile q4wine from master branch with '-DDEBUG=ON' option please?

Then I will need following info:
1. start q4wine from the terminal to capture the output.
2. run any wine app
3. goto 'process' tab
4. wail 5-10 seconds.
5. send the q4wine's output to me via email \ pastebin whatever
6. send the 'ps aux' output to me via email \ pastebin whatever

**Comment by tehnick** [comment]
![desktop_556](https://cloud.githubusercontent.com/assets/441190/13205960/6be7391c-d905-11e5-91ce-9e4ed9af560b.png)

Detailed logs I have sent to your email address.

**Comment by brezerk** [comment]
Thanks. Should be fixed now: https://github.com/brezerk/q4wine/commit/52a41414759fcc13ba7ef5bebf89d2610f5e9836

**Comment by tehnick** [comment]
Fixed. Thanks.
