### ISSUE TITLE
Winetricks' item description label doesn't wrap properly

### ISSUE THREAD

**Issue by ryux2** [brezerk/q4wine#71]
The label widget in the setup tab for winetricks configuration doesn't properly wrap causing the window to resize to fit the contents. The user can't shrink (width) the window until some other item with a shorter description is selected regardless of which tab is active. 

![screenshot from 2016-03-20 19-18-35](https://cloud.githubusercontent.com/assets/835622/13908048/7c29b502-eed1-11e5-9e75-762d3ce13132.png)
![screenshot from 2016-03-20 19-18-49](https://cloud.githubusercontent.com/assets/835622/13908050/7ea4477a-eed1-11e5-8b12-118bc26d3b9e.png)

**Comment by brezerk** [comment]
Thanks.

Should be fixed now: https://github.com/brezerk/q4wine/commit/6aece14ca2eb611938b21d6df61d1002394573ff

Reopen if needed.
