### ISSUE TITLE
Qt5: detailed view item selection duplicate 

### ISSUE THREAD

**Issue by pchome** [brezerk/q4wine#75]
![img](http://i.imgur.com/WCztKnA.png)

Every selected item works, but selection duplicated on next item.
Same for Xfce4 and KDE5 environments, Qt5 build.

**Comment by brezerk** [comment]
yeah. I was wondering if this was issue with my qt build or not :)

**Comment by brezerk** [comment]
Should be fixed now: https://github.com/brezerk/q4wine/commit/2b5cfebc41ca9c0cf80760f56b955ea7c68c9553

**Comment by brezerk** [comment]
Reopen if needed
