### ISSUE TITLE
[regression, bisected] Icon information is not displayed correctly

### ISSUE THREAD

**Issue by kakurasan** [brezerk/q4wine#80]
![q4wine-1 3 1-programs-icon-information](https://cloud.githubusercontent.com/assets/10556453/17088929/3ee77244-525c-11e6-8577-bbe38038720a.png)

"Program:", "Args:", and "Description:" are always *empty*.
"Runs in console:" is always "*No*".
"Desktop size:" is always "*Default*".

----- Result of "git bisect" -----
2b5cfebc41ca9c0cf80760f56b955ea7c68c9553 is the first bad commit
commit 2b5cfebc41ca9c0cf80760f56b955ea7c68c9553
Author: Alexey S. Malakhov &lt;brezerk AT gmail DOT com&gt;
Date:   Tue May 17 17:29:09 2016 +0300

    BUG-75: Qt5: detailed view item selection duplicate;

**Comment by brezerk** [comment]
Thank a lot. Working in the fix now.

**Comment by brezerk** [comment]
*sigh*

Debug leftover was removed. This commit https://github.com/brezerk/q4wine/commit/e8c90a2f08ac871a6c9a3ac6cdc63f5f946d4661 should fix the issue.

Thanks a lot for the reporting and for the bisect.

Reopen if needed.
