### ISSUE TITLE
First startup wizard (quick mount profile): profile strings are initially empty if fuseiso is not installed

### ISSUE THREAD

**Issue by kakurasan** [brezerk/q4wine#81]
![q4wine-1 3 1-firststartupwizard-quickmount](https://cloud.githubusercontent.com/assets/10556453/17214768/6d970ec2-5515-11e6-8dac-727e378af9dc.png)

"sudo" is the default profile, but the line edits for profile strings are *initially* empty.

**Comment by brezerk** [comment]
Hm......

Hi @kakurasan which one version it is?

I can't reproduce this on the latest trunk build: 
![screenshot_20160729_102206](https://cloud.githubusercontent.com/assets/23820/17240835/72caec4a-5576-11e6-8059-ff9b4c6ed588.png)

**Comment by brezerk** [comment]
Also, do you get mount string set in case if you select "gui sudo" profile?

**Comment by kakurasan** [comment]
I noticed that fuseiso was not installed. After installing it, "FuseISO" is the default profile and the strings for profile "FuseISO" are displayed.

> Are you getting mount strings set in case if you select "gui sudo" profile?

Yes. The strings for profile "gui sudo" are displayed.

The version is c7cf08f7a147642afd85952f65db6a5722d6a495.

**Comment by brezerk** [comment]
Yea, fuseiso must be a better choice then raw sudo :)

But yes, I was able to reproduce the issue now. Thanks for clarifications.

**Comment by brezerk** [comment]
Fixed: https://github.com/brezerk/q4wine/commit/a09b5b3034f2a49f342730148e1d3c506732ef7d

Thanks a lot for reporting. Reopen if needed.
