### ISSUE TITLE
Download (latest) Winetricks from GitHub

### ISSUE THREAD

**Issue by kakurasan** [brezerk/q4wine#82]
The latest version of Winetricks can be downloaded at GitHub (https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks).

This is HTTPS URL. Winetricks plugin needs to support HTTPS proxy ("https_proxy" environment variable).

**Comment by brezerk** [comment]
Wow. Thanks a lot for reporting.

Plugin code updated: https://github.com/brezerk/q4wine/commit/14e98d4f1e596e5b6ec60c75cc0a5df5ea744b83

Reopen if needed;

**Comment by ozky** [comment]
I have bug with winetricks weird categories when install it and update.
Seems to be releated to this bug if it's not i'll open new one.

![q4wine](https://cloud.githubusercontent.com/assets/1551665/19869981/367a47a0-9fb7-11e6-8f67-a293da7e2595.png)

**Comment by brezerk** [comment]
hi @ozky 

there was parser refactor just a moment ago, can you try latest trunk please?

**Comment by ozky** [comment]
Yes i can it will take bit time to compile it but do it later today.

**Comment by ozky** [comment]
I compiled it and problem is fixed.

**Comment by brezerk** [comment]
hi @ozky 

Thanks a lot for verification!
