### ISSUE TITLE
treat aarch64 as 64 bit platform and put libraries in lib64 directory

### ISSUE THREAD

**Issue by nullr0ute** [brezerk/q4wine#85]
Bug-50 (according to the changelog) added support for lib64 for x86_64. aarch64 is also supported by wine is a 64 bit platform and should be treated the same.

**Comment by brezerk** [comment]
Hi @nullr0ute 

Not sure what I need to do here. BUG-50 intended to simplify wine lib's configuration for q4wine, by allowing Wine itself to care of this.  So  this settings are optional for q4wine currently (as for 1.3.x).

I have no aarch64 system to test unfortunately can you clarify the issue and requirements please?

Thanks.

**Comment by nullr0ute** [comment]
Basically the libs need to be installed into /usr/lib64/ instead of /usr/lib/ when the architecture is aarch64. Full build logs here of a aarch64 build. Happy to test any patches etc

http://arm.koji.fedoraproject.org/kojifiles/work/tasks/3038/3683038/build.log

**Comment by brezerk** [comment]
Hi @nullr0ute,

Thanks for clarifications!

This commit https://github.com/brezerk/q4wine/commit/33939d9860a519412e76e0f2e150fd7d35f89824 change cmake build script logic to set target directory to the /usr/lib64/ when the architecture is aarch64.

Let me know if it works for you or not ( I hope it does :) )

**Comment by nullr0ute** [comment]
Looks good! Thanks for the quick response :)

**Comment by brezerk** [comment]
Thanks for reporting and testing!
