### ISSUE TITLE
Console launch environment uses dead setting fields

### ISSUE THREAD

**Issue by RomanHargrave** [brezerk/q4wine#90]
When launching a console within a prefix, q4wine sets several variables that are useful for scripts, etc, which need to know information about what version of wine is needed for a session.

q4wine attempts to add some of those, but ultimately fails as the routine which launches the terminal does not use what I assume is the new version management system and instead expects specific setting fields to be populated.

```cpp
sh_args << "env";
sh_args << QString("WINEPREFIX=%1").arg(prefix_info.value("path"));
if (!prefix_info.value("libs").isEmpty())
    sh_args << QString("WINEDLLPATH=%1").arg(prefix_info.value("libs"));
sh_args << QString("WINELOADER=%1").arg(prefix_info.value("loader"));
sh_args << QString("WINESERVER=%1").arg(prefix_info.value("server"));
if (!prefix_info.value("arch").isEmpty())
    sh_args << QString("WINEARCH=%1").arg(prefix_info.value("arch"));
```

**Comment by brezerk** [comment]
Hi @RomanHargrave which one wine version are you using?

From what I see this settings are still actual for 1.9.21 also they are listed in the official wiki https://www.winehq.org/docs/wine

**Comment by brezerk** [comment]
Oh. Never mind i got your message now :)

This commit should fix the issue https://github.com/brezerk/q4wine/commit/2db0bb08fe46fb334ff528e2d3c1939ef4dd7bce

Thanks a lot for reporting. Reopen if needed.
