### ISSUE TITLE
Add WINE env var to console environment

### ISSUE THREAD

**Issue by RomanHargrave** [brezerk/q4wine#91]
Many programs, primarily winetricks in my case, will launch the system wine if they don't know what version of wine to use for a particular prefix. Setting `WINE` to the path to the correct wine fixes this issue.

**Comment by brezerk** [comment]
Hi @RomanHargrave 

Thanks for report.
WINE environment variable was added as requested with this commit: https://github.com/brezerk/q4wine/commit/608c222317f280d781d9bca65bd102d86150e963

Test it please. Feel free to reopen ticket if needed.

Thanks.

**Comment by RomanHargrave** [comment]
verified fixed wrt adding env var.
