### ISSUE TITLE
Regression 2db0bb0: WINEPREFIX not set in console 

### ISSUE THREAD

**Issue by RomanHargrave** [brezerk/q4wine#92]
2db0bb0 fixed environment prep for console sessions, but appears to have removed the `WINEPREFIX` environment, or at least it's not set for me, despite the fact that it should be set.

I would like to suggest that the console launch is rewritten such that the environment is built with `env` and then the terminal emulator is started, rather than building a command string to pass to the emulator.

e.g. `env <parts=value> /path/to/terminal <args> ...` 

---

Debug output supports the lack of `WINEPREFIX` @ 2db0bb0

```
[ii] Open console args: ("-e", "env WINE='/opt/wine/1.9.20-staging/bin/wine' WINEDLLPATH='/opt/wine/1.9.20-staging/lib' WINELOADER='/opt/wine/1.9.20-staging/bin/wine' WINESERVER='/opt/wine/1.9.20-staging/bin/wineserver' WINEARCH=win32 /bin/sh -c "cd '/home/roman/.local/share/wineprefixes/CRYSIS' && echo '' && echo ' [ii] wine environment variables are set to \"compatible_games\" prefix settings.' && echo '' && /usr/local/bin/fish "") 
```

**Comment by brezerk** [comment]
>e.g. env <parts=value> /path/to/terminal <args> ...

Yea, make sense. Will refactor a bit. Thank you.
