### ISSUE TITLE
q4wine prevents user from running winecfg from KRunner even after uninstalling

### ISSUE THREAD

**Issue by ezxpro** [brezerk/q4wine#98]
I had a problem with q4wine in KDE 5.8.3 on Arch Linux when trying to launch winecfg after q4wine was uninstalled and found out it applies for other wine builtin utilities as well.

The problem is that q4wine creates several .desktop files at `$HOME/.local/share/applications/q4wine/Default/system/ ` which aren't removed once the program is uninstalled.

Those files will override the corresponding commands in KRunner - funilly it only overrides iexplore, taskmgr, regedit and oleview, the others can still be launched because the real command's entry appears right below the buggy entry, but pressing enter will try launching the troubled one - thus making it impossible to run some of them (namely `regedit`, `winecfg`, `iexplore`, `explorer`, `taskmgr` as a few others) in KDE unless you do it from the command line.

 Clicking in the entries will return the message "Could not find the program '/usr/bin/q4wine-cli"'.
Finally, I think these files should be removed once the program is uninstalled, since they are created anyway when you install q4wine.

**Comment by brezerk** [comment]
Hi @ezxpro 

Not sure how to help. `$HOME/.local/share/applications/q4wine/Default/system/` in not created when you install q4wine. It is actually run time data:

This structure is created via `Desktop menu` plugin and should reflect q4wine's prefix structure.

There is possibility to disable the plugin, and even remove  all generated data via 'File -> Options -> Plugins -> Desktop menu'

And even more, q4wine does not have any uninstall target, so this part is managed by your current pkg maintainer and/or pkg manager.

One thing I can do here: document this 'feature'

**Comment by ezxpro** [comment]
Hello again, Alexey.
Alright, I think documenting this feature could be a good idea :+1:
But anyhow I find it interesting that you mentioned that q4wine not having any uninstall target, this should be handled by the package maintainer. (PS: Do you think I should contact this person?)

In addition, it might be interesting to know that after deleting these files at the mentioned location one might still have problems with the overriding of these commands. I asked for help in KDE's forums and found out that this happens because KDE might cache these files. Rebooting the computer or executing `kbuildsycoca5` might clean your cache and solve the problem.

**Comment by brezerk** [comment]
hi @ezxpro 

>Do you think I should contact this person?

To be honest I am not sure. PKG manager does not supposed to remove any runtime or user-data, only the files which was deployed with the package itself. So I am 99% sure that any request of this kind will be declined...

And for q4wine it is impossible to detect when it is a subject of removal. Even I will implement `make uninstall` target, this will not help: most of pkg managers does not operate with sources, especially for pkg removal.

>Rebooting the computer or executing kbuildsycoca5 might clean your cache and solve the problem.

It is correct. Most of  package manager are executing `kbuildsycoca5` (if kde was detected on this system) as a part of *.desktop files removal or deployment.

**Comment by brezerk** [comment]
Sorry. it took me ages. But I actually documented this behavior: https://github.com/brezerk/q4wine/commit/84bdef061a63b67907f5362e7ef0ac5880327071 :)

Thanks for reporting. 
Closing, reopen if needed.

**Comment by ezxpro** [comment]
Oh, thanks for notifying me.

Currently I am not using wine and related tools in my build, as I'm not
needing it, but anyhow, the time gap between the reporting and your action
towards the problem, I feel very glad that I did something useful by
reporting, and even gladder that you contacted me back to inform me of the
current situation. Most of the times I report a bug I'm never answered back.

So, my special thanks for you too.

Goodbye.

2017-10-09 17:42 GMT-03:00 Alexey S. Malakhov <notifications@github.com>:

**Comment by ezxpro** [comment]
And by the way, I'm just curious but what sort of programming you do
professionally (web, system, mobile...)?

2017-10-09 19:02 GMT-03:00 Ezequiel Santos <ezequiel.ezb@gmail.com>:

**Comment by brezerk** [comment]
well.. system and web mostly. last few years I was working as devops engineer. jfyi: http://brezblock.org.ua/contacts/#skills
